CREATE TABLE users (
  id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  username varchar(500) NOT NULL,
  email varchar(500) NOT NULL,
  password_hash varchar(500) NOT NULL
);

CREATE UNIQUE INDEX users_email_idx ON users (email);
CREATE UNIQUE INDEX users_username_idx ON users (username);

--gopg:split

CREATE TABLE articles (
  id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  content varchar(500) NOT NULL,
  user_id int8 NOT NULL REFERENCES users (id) ON DELETE CASCADE,

  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);